List Files for Debugging

diff --git a/.github/workflows/workflows.yaml b/.github/workflows/workflows.yaml
--- a/.github/workflows/workflows.yaml
+++ b/.github/workflows/workflows.yaml
@@ -40,16 +40,19 @@ jobs:
           name: test-results
           path: src/VarzeaTeam.Test/TestResults
 
-      - name: Debug - List all files
-        run: find . -type f
+      - name: Debug - List all files in the workspace
+        run: find ${{ github.workspace }} -type f
 
       - name: Debug - List TestResults directory
         run: ls -R src/VarzeaTeam.Test/TestResults
 
+      - name: Debug - Show coverage report file
+        run: cat src/VarzeaTeam.Test/TestResults/coverage.cobertura.xml || echo "Coverage file not found"
+
       - name: Code Coverage Report
         uses: irongut/CodeCoverageSummary@v1.3.0
         with:
-          filename: src/VarzeaTeam.Test/TestResults/**/coverage.cobertura.xml
+          filename: src/VarzeaTeam.Test/TestResults/coverage.cobertura.xml
           badge: true
           fail_below_min: true
           format: markdown
